In [1]:
import numpy as np
import itertools
import scipy
from SINDyFunctions import *

In [2]:
# ---simulate Lorenz system and add noise---
# system parameters
beta = 1

# simulate
X0 = np.array([1,1])
t_sim = 10
gridDensity = 100
t_span = [0,t_sim]
t_out,X_clean,XD_out = simulateLV(X0,t_sim,gridDensity,beta)

# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.5
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# SINDy
w_ident_SINDy = SINDy_VDP(t_out,X_clean,params_regression,polyOrder=5)
w_ident_SINDy

array([[ 0.        ,  0.        ],
       [ 0.        , -5.95735141],
       [ 2.99645702,  0.        ],
       [ 0.        ,  0.        ],
       [-1.00035242,  0.99673458],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

In [3]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.5
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# FFT WSINDy
w_ident_WSINDy_FFT = WSINDy_Fourier_FFT_VDP(t_out,X_clean,60,params_regression,polyOrder=5)
w_ident_WSINDy_FFT

array([[ 0.        ,  0.        ],
       [ 0.        , -5.9768486 ],
       [ 3.031728  ,  0.        ],
       [ 0.        ,  0.        ],
       [-1.00318499,  1.00008655],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

In [4]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.3
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

w_ident_WSINDy_bump = WSINDy_bump_VDP(t_out,X_clean,20,20,params_regression,polyOrder=5)
w_ident_WSINDy_bump

d:\Cornell University\C3 Group\SINDy\Code\FourierBasedWeakSINDy\SINDyFunctions.py:407: RuntimeWarning: overflow encountered in scalar multiply
  C = 1/(p**p*q**q)*((p+q)/(b-a))**(p+q)
d:\Cornell University\C3 Group\SINDy\Code\FourierBasedWeakSINDy\SINDyFunctions.py:411: RuntimeWarning: overflow encountered in scalar multiply
  C = 1/(p**p*q**q)*((p+q)/(b-a))**(p+q)


array([[ 0.        ,  0.        ],
       [ 0.        , -5.98534231],
       [ 3.0026803 ,  0.        ],
       [ 0.        ,  0.        ],
       [-1.00413077,  1.00090314],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

In [5]:
_,exps = calcTheta_poly_2D(t_out[1:-1],X_clean[1:-1,0],X_clean[1:-1,1])
w_true = trueCoeffMatrix_LV(exps,beta)
w_true

array([[ 0.,  0.],
       [ 0., -6.],
       [ 3.,  0.],
       [ 0.,  0.],
       [-1.,  1.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])