In [1]:
import numpy as np
import itertools
import scipy
from SINDyFunctions import *

In [2]:
# ---simulate Lorenz system and add noise---
# system parameters
sigma = 10
rho = 28
beta = 8/3

# simulate
X0 = np.array([20,12,-30])  # initial conditions
t_sim = 10
gridDensity = 1000  # number of steps in one second
[t_out,X_clean,X_dot_out] = simulateLorenzSystem(X0,t_sim,gridDensity,sigma,rho,beta)

# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.5
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# SINDy
w_ident_SINDy = SINDy_Lorenz(t_out,X_clean,params_regression,polyOrder=5)
w_ident_SINDy

array([[  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,  -2.6623548 ],
       [ 10.00345599,  -1.00192575,   0.        ],
       [-10.00346214,  27.94974863,   0.        ],
       [  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ],
       [  0.        ,  -0.9968485 ,   0.        ],
       [  0.        ,   0.        ,   0.9981354 ],
       [  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ],
       [  0.        ,   0.     

In [3]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.5
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# FFT WSINDy
w_ident_WSINDy_FFT = WSINDy_FFT_PSD_3D(t_out,X_clean,100,params_regression,polyOrder=2)
w_ident_WSINDy_FFT

array([[ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        , -2.71790258],
       [ 9.96753533, -0.99283212,  0.        ],
       [-9.97976142, 27.82910502,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        , -0.99385833,  0.        ],
       [ 0.        ,  0.        ,  1.00398505],
       [ 0.        ,  0.        ,  0.        ]])

In [4]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.3
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

w_ident_WSINDy_bump = WSINDy_bump_Lorenz(t_out,X_clean,20,20,params_regression,polyOrder=5)
w_ident_WSINDy_bump

d:\Cornell University\C3 Group\SINDy\Code\FourierBasedWeakSINDy\Tests\SINDyFunctions.py:630: RuntimeWarning: overflow encountered in scalar multiply
  C = 1/(p**p*q**q)*((p+q)/(b-a))**(p+q)
d:\Cornell University\C3 Group\SINDy\Code\FourierBasedWeakSINDy\Tests\SINDyFunctions.py:634: RuntimeWarning: overflow encountered in scalar multiply
  C = 1/(p**p*q**q)*((p+q)/(b-a))**(p+q)


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0

In [5]:
_,exps = calcTheta_poly_2D(t_out[1:-1],X_clean[1:-1,0],X_clean[1:-1,1])
w_true = trueCoeffMatrix_LV(exps,beta)
w_true

array([[ 0.        ,  0.        ],
       [ 0.        , -6.        ],
       [ 3.        ,  0.        ],
       [ 0.        ,  0.        ],
       [-2.66666667,  2.66666667],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])