In [40]:
import numpy as np
import itertools
import scipy
from SINDyFunctions import *

In [68]:
# ---simulate Lorenz system and add noise---
# system parameters
mu = 10

# simulate
X0 = np.array([1,1])
t_sim = 30
gridDensity = 100
t_span = [0,t_sim]
t_out,X_clean,XD_out = simulateVDP(X0,t_sim,gridDensity,mu)

# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.5
params_regression["lambda_ridge"] = 0.0
params_regression["N_loops"] = 100

# SINDy
w_ident_SINDy = SINDy_VDP(t_out,X_clean,params_regression,polyOrder=3)
w_ident_SINDy

array([[ 0.        ,  0.        ],
       [ 0.99853687,  9.93852347],
       [ 0.        , -0.99862893],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        , -9.92402186],
       [ 0.        ,  0.        ]])

In [70]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.1
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# FFT WSINDy
w_ident_WSINDy_FFT = WSINDy_FFT_PSD_2D(t_out,X_clean,100,params_regression,polyOrder=5)
w_ident_WSINDy_FFT

array([[ 0.        ,  0.        ],
       [ 1.00011938,  9.90924641],
       [ 0.        , -0.98792149],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        , -9.68326864],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        , -0.10593886],
       [ 0.        ,  0.        ]])

In [71]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.2
params_regression["lambda_ridge"] = 0.0
params_regression["N_loops"] = 100

w_ident_WSINDy_bump = WSINDy_bump_VDP(t_out,X_clean,20,20,params_regression,polyOrder=3)
w_ident_WSINDy_bump

array([[ 0.        ,  0.        ],
       [ 1.00005054,  9.9779375 ],
       [ 0.        , -0.99833045],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        , -9.97541234],
       [ 0.        ,  0.        ]])

In [51]:
Theta,exps = calcTheta_poly_2D(t_out[1:-1],X_clean[1:-1,0],X_clean[1:-1,1],order=5)
w_true = trueCoeffMatrix_VDP(exps,mu)
w_true

array([[  0.,   0.],
       [  1.,  10.],
       [  0.,  -1.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0., -10.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.]])