In [22]:
import numpy as np
import itertools
import scipy
from SINDyFunctions import *

In [23]:
# ---simulate Lorenz system and add noise---
# system parameters
beta = 1

# simulate
X0 = np.array([1,1])
t_sim = 10
gridDensity = 1000
t_span = [0,t_sim]
t_out,X_clean,XD_out = simulateLV(X0,t_sim,gridDensity,beta)

# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.5
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# SINDy
w_ident_SINDy = SINDy_VDP(t_out,X_clean,params_regression,polyOrder=5)
w_ident_SINDy

array([[ 0.        ,  0.        ],
       [ 0.        , -5.97096254],
       [ 3.00192264,  0.        ],
       [ 0.        ,  0.        ],
       [-1.00217745,  0.99901284],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

In [24]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.5
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# FFT WSINDy
w_ident_WSINDy_FFT = WSINDy_FFT_PSD_2D(t_out,X_clean,100,params_regression,polyOrder=5)
w_ident_WSINDy_FFT

array([[ 0.        ,  0.        ],
       [ 0.        , -5.97100545],
       [ 3.02942052,  0.        ],
       [ 0.        ,  0.        ],
       [-1.00236056,  0.99912562],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

In [25]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.3
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

w_ident_WSINDy_bump = WSINDy_bump_VDP(t_out,X_clean,20,20,params_regression,polyOrder=5)
w_ident_WSINDy_bump

array([[ 0.        ,  0.        ],
       [ 0.        , -5.9853292 ],
       [ 3.00269663,  0.        ],
       [ 0.        ,  0.        ],
       [-1.00413693,  1.00090165],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

In [26]:
_,exps = calcTheta_poly_2D(t_out[1:-1],X_clean[1:-1,0],X_clean[1:-1,1])
w_true = trueCoeffMatrix_LV(exps,beta)
w_true

array([[ 0.,  0.],
       [ 0., -6.],
       [ 3.,  0.],
       [ 0.,  0.],
       [-1.,  1.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])