In [5]:
import numpy as np
import itertools
import scipy
from SINDyFunctions import *

In [6]:
# ---simulate Lorenz system and add noise---
# system parameters
a = 10
b = 2.667
c = 28
d = 1.1

# simulate
X0 = np.array([5,8,12,21])
t_sim = 10
gridDensity = 1000
t_span = [0,t_sim]
t_out,X_clean = simulateHyperLorenz(X0,t_sim,gridDensity,a,b,c,d)

# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.5
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# SINDy
w_ident_SINDy = SINDy_4D(t_out,X_clean,params_regression,polyOrder=3)
w_ident_SINDy

array([[  0.        ,   0.        ,   0.        ,   0.        ],
       [  1.00020522,   0.        ,   0.        ,   1.09934535],
       [  0.        ,   0.        ,  -2.6701817 ,   0.        ],
       [ 10.00290791,  -0.98039932,   0.        ,   0.        ],
       [-10.00324654,  27.91448343,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,  -0.99632002,   0.        ,  -0.99867023],
       [  0.        ,   0.        ,   0.99898426,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0

In [ ]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.5
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# FFT WSINDy
w_ident_WSINDy_FFT = WSINDy_FFT_PSD_4D(t_out,X_clean,100,params_regression,polyOrder=3)
w_ident_WSINDy_FFT

array([[  0.        ,   0.        ,   0.        ,   0.        ],
       [  1.00055729,   0.        ,   0.        ,   1.09732661],
       [  0.        ,   0.        ,  -2.67607015,   0.        ],
       [  9.9956176 ,  -0.9633323 ,   0.        ,   0.        ],
       [-10.00187305,  27.88229467,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,  -0.99580016,   0.        ,  -0.9989262 ],
       [  0.        ,   0.        ,   0.99924031,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0

In [8]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.1
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# bump WSINDy
w_ident_WSINDy_bump = WSINDy_bump_4D(t_out,X_clean,20,20,params_regression,polyOrder=3)
w_ident_WSINDy_bump

d:\Cornell University\C3 Group\SINDy\Code\FourierBasedWeakSINDy\Tests\SINDyFunctions.py:630: RuntimeWarning: overflow encountered in scalar multiply
  C = 1/(p**p*q**q)*((p+q)/(b-a))**(p+q)
d:\Cornell University\C3 Group\SINDy\Code\FourierBasedWeakSINDy\Tests\SINDyFunctions.py:634: RuntimeWarning: overflow encountered in scalar multiply
  C = 1/(p**p*q**q)*((p+q)/(b-a))**(p+q)


array([[  0.        ,   0.        ,   0.        ,   0.        ],
       [  1.00006078,   0.        ,   0.        ,   1.10150209],
       [  0.        ,   0.        ,  -2.667578  ,   0.        ],
       [ 10.00092396,  -1.01004514,   0.        ,   0.        ],
       [-10.00060072,  27.80159563,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,  -0.99223471,   0.        ,  -0.99991717],
       [  0.        ,   0.        ,   0.9983398 ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0

In [9]:
Theta,exps = calcTheta_poly_4D(t_out[1:-1],X_clean[1:-1,0],X_clean[1:-1,1],X_clean[1:-1,2],X_clean[1:-1,3])
w_true = trueCoeffMatrix_hyperLorenz(exps,a,b,c,d)
w_true

array([[  0.   ,   0.   ,   0.   ,   0.   ],
       [  1.   ,   0.   ,   0.   ,   1.1  ],
       [  0.   ,   0.   ,  -2.667,   0.   ],
       [ 10.   ,  -1.   ,   0.   ,   0.   ],
       [-10.   ,  28.   ,   0.   ,   0.   ],
       [  0.   ,   0.   ,   0.   ,   0.   ],
       [  0.   ,   0.   ,   0.   ,   0.   ],
       [  0.   ,   0.   ,   0.   ,   0.   ],
       [  0.   ,   0.   ,   0.   ,   0.   ],
       [  0.   ,   0.   ,   0.   ,   0.   ],
       [  0.   ,   0.   ,   0.   ,   0.   ],
       [  0.   ,   0.   ,   0.   ,   0.   ],
       [  0.   ,  -1.   ,   0.   ,  -1.   ],
       [  0.   ,   0.   ,   1.   ,   0.   ],
       [  0.   ,   0.   ,   0.   ,   0.   ],
       [  0.   ,   0.   ,   0.   ,   0.   ],
       [  0.   ,   0.   ,   0.   ,   0.   ],
       [  0.   ,   0.   ,   0.   ,   0.   ],
       [  0.   ,   0.   ,   0.   ,   0.   ],
       [  0.   ,   0.   ,   0.   ,   0.   ],
       [  0.   ,   0.   ,   0.   ,   0.   ],
       [  0.   ,   0.   ,   0.   ,   0.   ],
       [  