In [1]:
import numpy as np
import itertools
import scipy
from SINDyFunctions import *

In [2]:
# ---simulate Lorenz system and add noise---
# system parameters
a = 10
b = 28
c = 8/3
d = 1.3

# simulate
X0 = np.array([0.1,0.1,0.1,0.1])
t_sim = 10
gridDensity = 1000
t_span = [0,t_sim]
t_out,X_clean = simulateHyperJha(X0,t_sim,gridDensity,a,b,c,d)

# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.8
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# SINDy
w_ident_SINDy = SINDy_4D(t_out,X_clean,params_regression,polyOrder=3)
w_ident_SINDy

array([[  0.        ,   0.        ,   0.        ,   0.        ],
       [  1.00025993,   0.        ,   0.        ,   1.29747394],
       [  0.        ,   0.        ,  -2.66908005,   0.        ],
       [ 10.00422864,  -0.97339844,   0.        ,   0.        ],
       [-10.0037314 ,  27.88778683,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,  -0.99543722,   0.        ,  -0.99839242],
       [  0.        ,   0.        ,   0.9994431 ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0

In [3]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.5
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# FFT WSINDy
w_ident_WSINDy_FFT = WSINDy_FFT_PSD_4D(t_out,X_clean,100,params_regression,polyOrder=3)
w_ident_WSINDy_FFT

array([[  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.9996811 ,   0.        ,   0.        ,   1.29274668],
       [  0.        ,   0.        ,  -2.6804496 ,   0.        ],
       [  9.99869523,  -0.97460199,   0.        ,   0.        ],
       [-10.00189843,  27.87298457,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,  -0.99521822,   0.        ,  -0.99879748],
       [  0.        ,   0.        ,   0.99908876,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0

In [4]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.1
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# bump WSINDy
w_ident_WSINDy_bump = WSINDy_bump_4D(t_out,X_clean,20,20,params_regression,polyOrder=3)
w_ident_WSINDy_bump

d:\Cornell University\C3 Group\SINDy\Code\FourierBasedWeakSINDy\SINDyFunctions.py:629: RuntimeWarning: overflow encountered in scalar multiply
  C = 1/(p**p*q**q)*((p+q)/(b-a))**(p+q)
d:\Cornell University\C3 Group\SINDy\Code\FourierBasedWeakSINDy\SINDyFunctions.py:633: RuntimeWarning: overflow encountered in scalar multiply
  C = 1/(p**p*q**q)*((p+q)/(b-a))**(p+q)


array([[ 0.        ,  0.        , -0.22753521,  0.        ],
       [ 0.99999293,  0.        ,  0.        ,  1.29856537],
       [ 0.        ,  0.        , -2.67112949,  0.        ],
       [ 9.99990826, -0.98083673,  0.        ,  0.        ],
       [-9.99987038, 27.76141305,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.9906292 ,  0.        , -0.99895818],
       [ 0.        ,  0.        ,  1.00367186,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.

In [5]:
Theta,exps = calcTheta_poly_4D(t_out[1:-1],X_clean[1:-1,0],X_clean[1:-1,1],X_clean[1:-1,2],X_clean[1:-1,3])
w_true = trueCoeffMatrix_hyperJha(exps,a,b,c,d)
w_true

array([[  0.        ,   0.        ,   0.        ,   0.        ],
       [  1.        ,   0.        ,   0.        ,   1.3       ],
       [  0.        ,   0.        ,  -2.66666667,   0.        ],
       [ 10.        ,  -1.        ,   0.        ,   0.        ],
       [-10.        ,  28.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,  -1.        ,   0.        ,  -1.        ],
       [  0.        ,   0.        ,   1.        ,   0.        ],
       [  0.        ,   0.        ,   0.        ,   0.        ],
       [  0.        ,   0