In [1]:
import numpy as np
import itertools
import scipy
from SINDyFunctions import *

In [3]:
# ---simulate Lorenz system and add noise---
# system parameters
a = 0.2
b = 0.2
c = 5.7

# simulate
X0 = np.array([1,1,1])
t_sim = 30
gridDensity = 1000
t_span = [0,t_sim]
t_out,X_clean,X_dot_out = simulateRosslerSystem(X0,t_sim,gridDensity,a,b,c)

# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.01
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# SINDy
w_ident_SINDy = SINDy_Lorenz(t_out,X_clean,params_regression,polyOrder=5)
w_ident_SINDy

array([[ 0.        ,  0.        ,  0.20169732],
       [-0.99996392,  0.        , -5.73811703],
       [-1.00000374,  0.2000035 ,  0.        ],
       [ 0.        ,  1.00000427,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.00539926],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.   

In [6]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.02
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# FFT WSINDy
w_ident_WSINDy_FFT = WSINDy_FFT_PSD_3D(t_out,X_clean,100,params_regression,polyOrder=5)
w_ident_WSINDy_FFT

array([[ 0.        ,  0.        ,  0.        ],
       [-0.99982769,  0.        , -5.73468011],
       [-1.00001757,  0.19986801,  0.        ],
       [ 0.        ,  0.99968729,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.00494574],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.   

In [7]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.03
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# bump WSINDy
w_ident_WSINDy_bump = WSINDy_bump_Lorenz(t_out,X_clean,20,20,params_regression,polyOrder=5)
w_ident_WSINDy_bump

d:\Cornell University\C3 Group\SINDy\Code\FourierBasedWeakSINDy\SINDyFunctions.py:630: RuntimeWarning: overflow encountered in scalar multiply
  C = 1/(p**p*q**q)*((p+q)/(b-a))**(p+q)
d:\Cornell University\C3 Group\SINDy\Code\FourierBasedWeakSINDy\SINDyFunctions.py:634: RuntimeWarning: overflow encountered in scalar multiply
  C = 1/(p**p*q**q)*((p+q)/(b-a))**(p+q)


array([[ 0.        ,  0.        ,  0.        ],
       [-1.00005241,  0.        , -0.55777932],
       [-1.00000367,  0.20000314,  0.        ],
       [ 0.        ,  1.00000359,  0.        ],
       [ 0.        ,  0.        , -1.71586123],
       [ 0.        ,  0.        , -0.35855298],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.08010656],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.83077664],
       [ 0.        ,  0.        , -2.03612719],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.89874819],
       [ 0.        ,  0.        ,  0.47999714],
       [ 0.        ,  0.        ,  0.03716056],
       [ 0.        ,  0.        ,  0.35677065],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.   

In [10]:
Theta,exps = calcTheta_poly_3D(t_out[1:-1],X_clean[1:-1,0],X_clean[1:-1,1],X_clean[1:-1,2])
w_true = trueCoeffMatrix_Rossler(exps,a,b,c)
w_true

array([[ 0. ,  0. ,  0.2],
       [-1. ,  0. , -5.7],
       [-1. ,  0.2,  0. ],
       [ 0. ,  1. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  1. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ],
 