In [1]:
import numpy as np
import itertools
import scipy
from SINDyFunctions import *

In [2]:
# ---simulate Lorenz system and add noise---

# simulate
X0 = np.array([1,1,1,1])
t_sim = 30
gridDensity = 1000
t_span = [0,t_sim]
t_out,X_clean = simulateHyperRossler(X0,t_sim,gridDensity,0,0,0,0)

# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.01
params_regression["lambda_ridge"] = 0.005
params_regression["N_loops"] = 100

# SINDy
w_ident_SINDy = SINDy_4D(t_out,X_clean,params_regression,polyOrder=3)
w_ident_SINDy

array([[ 2.94093971e-02,  3.25039728e-01, -2.53618641e+07,
        -2.78669232e-01],
       [ 0.00000000e+00,  3.67539311e-01, -2.04640065e+04,
        -1.80519826e-01],
       [ 0.00000000e+00,  0.00000000e+00, -1.27246539e-01,
         0.00000000e+00],
       [ 0.00000000e+00,  6.38421313e-01,  1.25668324e+04,
         6.41572167e-01],
       [ 0.00000000e+00, -1.83423644e-01,  2.10823324e+06,
         9.02665513e-02],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.24695849e+00,
      

In [39]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.02
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# FFT WSINDy
w_ident_WSINDy_FFT = WSINDy_Fourier_FFT_4D(t_out,X_clean,60,params_regression,polyOrder=3)
w_ident_WSINDy_FFT

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00, -3.93351553e+02, -5.07688841e+02,
        -2.41697735e+02],
       [ 0.00000000e+00, -3.83220301e-01,  3.03436972e-01,
        -2.35343717e-01],
       [ 0.00000000e+00,  2.41861198e+02,  3.11332308e+02,
         1.48613299e+02],
       [ 2.12193362e+00,  3.49495960e+05, -7.39679524e+05,
         2.14639383e+05],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00],
       [ 0.00000000e+00, -7.60493779e-02, -3.40950933e-01,
      

In [29]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.1
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# bump WSINDy
w_ident_WSINDy_bump = WSINDy_bump_4D(t_out,X_clean,20,20,params_regression,polyOrder=3)
w_ident_WSINDy_bump

array([[ 0.        ,  0.        ,  3.03186827,  0.        ],
       [ 0.        ,  0.99983881,  0.        ,  0.        ],
       [-1.0001364 ,  0.        ,  0.        , -0.5307664 ],
       [-1.00014292,  0.25011242,  0.        ,  0.        ],
       [ 0.        ,  1.0006301 ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.00168316,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.

In [30]:
Theta,exps = calcTheta_poly_4D(t_out[1:-1],X_clean[1:-1,0],X_clean[1:-1,1],X_clean[1:-1,2],X_clean[1:-1,3])
w_true = trueCoeffMatrix_hyperRossler(exps,0,0,0,0)
w_true

array([[ 0.  ,  0.  ,  3.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  0.05],
       [-1.  ,  0.  ,  0.  , -0.5 ],
       [-1.  ,  0.25,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
 