In [1]:
import numpy as np
import itertools
import scipy
from SINDyFunctions import *

In [2]:
# ---simulate Lorenz system and add noise---
# system parameters
mu = 10

# simulate
X0 = np.array([1,1])
t_sim = 30
gridDensity = 100
t_span = [0,t_sim]
t_out,X_clean,XD_out = simulateVDP(X0,t_sim,gridDensity,mu)

# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.5
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# SINDy
w_ident_SINDy = SINDy_VDP(t_out,X_clean,params_regression,polyOrder=5)
w_ident_SINDy

array([[ 0.        ,  0.        ],
       [ 0.99853674,  9.93851932],
       [ 0.        , -0.9986288 ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        , -9.92401902],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ]])

In [20]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.6
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

# FFT WSINDy
w_ident_WSINDy_FFT = WSINDy_Fourier_FFT_VDP(t_out,X_clean,1000,params_regression,polyOrder=5)
w_ident_WSINDy_FFT

array([[ 0.        ,  0.        ],
       [ 0.99387546,  5.8900278 ],
       [ 0.        , -1.01949331],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.        , -3.08724057],
       [ 0.        ,  0.        ]])

In [6]:
# sparse regression settings
params_regression = dict()
params_regression["method"] = "ridge"
params_regression["lambda_sparse"] = 0.3
params_regression["lambda_ridge"] = 0.001
params_regression["N_loops"] = 100

w_ident_WSINDy_bump = WSINDy_bump_VDP(t_out,X_clean,20,20,params_regression,polyOrder=5)
w_ident_WSINDy_bump

array([[  0.        ,   0.        ],
       [  1.00004949,  -1.51148466],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        , -11.43687309],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        ,   0.82723379],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ],
       [  0.        ,   0.        ]])

In [5]:
Theta,exps = calcTheta_poly_2D(t_out[1:-1],X_clean[1:-1,0],X_clean[1:-1,1])
w_true = trueCoeffMatrix_VDP(exps,mu)
w_true

array([[  0.,   0.],
       [  1.,  10.],
       [  0.,  -1.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0., -10.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.]])